---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    k8s.eip.work/displayName: busybox
    k8s.eip.work/ingress: 'false'
    k8s.eip.work/service: none
    k8s.eip.work/workload: cloud-busybox
  creationTimestamp: '2020-05-12T10:08:36Z'
  generation: 2
  labels:
    k8s.eip.work/layer: cloud
    k8s.eip.work/name: cloud-busybox
  name: cloud-busybox
  namespace: cm-sites
  resourceVersion: '11639962'
  selfLink: /apis/apps/v1/namespaces/cm-sites/deployments/cloud-busybox
  uid: 47a133ab-cff5-42dd-810a-04884e111b3d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.eip.work/layer: cloud
      k8s.eip.work/name: cloud-busybox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.eip.work/layer: cloud
        k8s.eip.work/name: cloud-busybox
    spec:
      containers:
        - command:
            - sleep
            - '3600'
          image: 'busybox:1.29'
          imagePullPolicy: IfNotPresent
          name: busybox
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-05-12T10:13:38Z'
      lastUpdateTime: '2020-05-12T10:13:38Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-05-12T10:08:36Z'
      lastUpdateTime: '2020-05-12T10:13:38Z'
      message: ReplicaSet "cloud-busybox-d89f4c694" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
